version: '3.8'

services:
  mora-shortlink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mora-shortlink-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/app/data/mora_shortlink.db
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).end()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  logs:
    driver: local
